// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzYtlFCaphZSNrRnISA2sdR4KahEjWGyU',
    appId: '1:650028489744:web:0d677dd81e2004e40f3e95',
    messagingSenderId: '650028489744',
    projectId: 'here-with-you-f9514',
    authDomain: 'here-with-you-f9514.firebaseapp.com',
    storageBucket: 'here-with-you-f9514.firebasestorage.app',
    measurementId: 'G-H2LDQJCPT0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6f1ZS4fx2URruunYn-8vmw-HQKed_PnM',
    appId: '1:650028489744:android:1d449e562d8905000f3e95',
    messagingSenderId: '650028489744',
    projectId: 'here-with-you-f9514',
    storageBucket: 'here-with-you-f9514.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1sMmIjsExYMIyXIEDVEWOyonNyHAVdZE',
    appId: '1:650028489744:ios:7acc3a8fb828031d0f3e95',
    messagingSenderId: '650028489744',
    projectId: 'here-with-you-f9514',
    storageBucket: 'here-with-you-f9514.firebasestorage.app',
    iosBundleId: 'com.example.hereWithYou',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1sMmIjsExYMIyXIEDVEWOyonNyHAVdZE',
    appId: '1:650028489744:ios:7acc3a8fb828031d0f3e95',
    messagingSenderId: '650028489744',
    projectId: 'here-with-you-f9514',
    storageBucket: 'here-with-you-f9514.firebasestorage.app',
    iosBundleId: 'com.example.hereWithYou',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzYtlFCaphZSNrRnISA2sdR4KahEjWGyU',
    appId: '1:650028489744:web:74b17749fda22ce40f3e95',
    messagingSenderId: '650028489744',
    projectId: 'here-with-you-f9514',
    authDomain: 'here-with-you-f9514.firebaseapp.com',
    storageBucket: 'here-with-you-f9514.firebasestorage.app',
    measurementId: 'G-EVN70ZMLL9',
  );
}
